general {
    lock_cmd = omarchy-system-lock
    before_sleep_cmd = OMARCHY_LOCK_ONLY=true omarchy-system-lock
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on
    inhibit_sleep = 3
}

# Start screensaver after 10 minutes
listener {
    timeout = 600
    on-timeout = pidof hyprlock || omarchy-launch-screensaver
}

# Lock system after 15 minutes WITHOUT turning display off
listener {
    timeout = 900
    on-timeout = OMARCHY_LOCK_ONLY=true omarchy-system-lock
    on-resume = omarchy-system-wake
}
